version: "3.2"

services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Asia/Ho_Chi_Minh"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
